version: '3.7'
services:
    fastapi:
        build:
            context: fastapi
        volumes:
        - ./appdata/py_engine/main.py:/app/main.py
        - ./appdata/logs/py_engine.log:/app/py_engine.log
        ports:
            - 8001:8001
    log_service:
        build: ./tailon
        volumes:
        - ./appdata/logs/py_engine.log:/logs/py_engine.log
        - ./appdata/logs/r_engine.log:/logs/r_engine.log
        ports:
          - 8081:8081
    load_testing_service:
        build: ./locust
        volumes:
        - ./appdata/load_test/:/load_test/
        ports:
            - 8089:8089
    prometheus:
        build: ./prometheus
        volumes:
            - ./appdata/prometheus/config.yml:/etc/prometheus/prometheus.yml
        ports:
            - 9090:9090
    grafana:
        build: ./grafana
        volumes:
            - ./appdata/grafana/config.ini:/etc/grafana/grafana.ini
            - ./appdata/grafana/datasource.yaml:/etc/grafana/provisioning/datasources/default.yaml
            - ./appdata/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/default.yaml
            - ./appdata/grafana/dashboards:/var/lib/grafana/dashboards
        ports:
            - 3000:3000
    plumber:
        build: ./plumber
        volumes:
            - ./appdata/r_engine/api.R:/app/api.R
            - ./appdata/r_engine/plumber.R:/app/plumber.R
            - ./appdata/logs/r_engine.log:/app/r_engine.log
        depends_on:
            - fastapi
        ports: 
            - 8000:8000